### ISSUE TITLE
Linter causes cursor to move to next line

### ISSUE THREAD

**Issue by watzon** [vlang/vscode-vlang#113] opened 2020-01-17 20:36 UTC
When the linter runs and it attempts to compile the current file it's forcing the cursor to move to the next line. It's manageable with a longer auto save delay, but with a shorter one it makes things down right unusable.

**Comment by danieldaeschle** [comment] 2020-12-17 11:40
is it still reproducable?

**Comment by danieldaeschle** [comment] 2020-12-17 11:41
Will close it due to https://github.com/vlang/vscode-vlang/issues/178

**Closed by danieldaeschle** 2020-12-17 11:41 UTC
